### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by MiguelCompany** [eProsima/Fast-RTPS#468]
**v1.8.0** is scheduled for **release on May 14th, 2019**

The following list of features was frozen **(API freeze) on Apr 12th, 2019**
- [x] IDL 4.2 [#460, ~~#464~~]
- [x] Deadline QoS [#446]
- [x] Lifespan QoS [#459]
- [x] Disable positive ACKs [#477, #508]
- [x] TLS support (secure sockets on TCP transport) [#410]
- [x] Realtime improvements
  - [x] Preallocation (design in #344)
    - [x] Fixed size strings [#361]
    - [x] Fixed size bitmaps [#370]
    - [x] Removing ParameterList_t [#379]
    - [x] Resource limited vector [#386]
    - [x] Matched readers allocation QoS on WriterAttributes [#406]
    - [x] ~~Allocation QoS [#479]~~
      - [x] Matched writers allocation QoS on ReaderAttributes [~~#436~~]
      - [x] Allocation QoS on RTPSParticipantAttributes
        - [x] Remote locators management [~~#462~~]
        - [x] Total number of participants, readers and writers QoS [~~#469~~]
  - [x] Best-effort writers write call converted to non-blocking [#426]
- [x] API improvements
  - [x] Configuration parameter for mutation tries [#467]
  - [x] Duration parameters using nanoseconds [#488]
  - [x] Well-known port calculation on endpoint custom locators [#475]
  - [x] Filter non-local addresses on whitelist [#476]
  - [x] Manual liveliness API (implementation pending for a patch release) [#487]

Other improvements and bugfixes:
- [x] Making lossy tests deterministic [#481]
- [x] ReaderProxy history reloaded incorrectly missing GAP message [~~#453~~, #502]
- [x] Optimize StatefulWriter.check_acked_status [~~#445~~ => #515]
- [x] RTPS Domain hostid part of the GUID match first interface IP [#458]
- [x] Windows: No need to expose linked libs when the target is a shared lib [#448]
- [x] Limitation on the Domain ID [#496]
- [x] Fix for #457 [#505]

Final PR #518

**Comment by MiguelCompany** [comment]
Allocatio QoS didn't make it to the release. It still has some failing tests.
