### ISSUE TITLE
Release 1.8.2

### ISSUE THREAD

**Issue by MiguelCompany** [eProsima/Fast-RTPS#709]
A patch release for 1.8.x branch, not scheduled yet

### Fixes
- [x] #641 -> cfaf5307dae3ab94e6ff929f7507779585895691

### Enhancements
- [x] #726: Assertion of participant liveliness receiving any RTPS message
- [x] #724: Multiple initial PDP announcements
- [x] #739 + #740 + #745: Flag to avoid multicast metatraffic

### Cherry picks
- [x] #585 -> eabb3fd757cc43823d54830519ac9b885aab836d
- [x] #598 -> 60a4c9bdff9fffbea1326264e16d6e8e7c76365b
- [x] #632 -> 83327764c9e75f8520a4d0c18dc7e37b202586e1
- [x] #676 -> 9cdac387cccf337037d0c726a04998e8b2af31b2
- [x] #688 -> f46ee325a66159fb8d7303c59d0833ac199af994
- [x] #694 -> 0b0158c3b8ec4e5504d0585bbecd2bd5fe6dfe60
- [x] #695 -> 8b1c1754c33b569ebfcfb8996e5dbe51f09f5c5c
- [x] #698 -> 6de8c6266744c704be52ff159b83ec647092793b
- [x] #659 -> 43b5b9aff68c6c70b1db9278d6ab84223931abcb
- [x] #622 -> 0308e04364b424894f6800975679e0a9390ab1f1
- [x] #652 -> 4fb4381eff49e534bed8f810518d10765757c899
- [x] #606 -> e9a593c48edd60c22eaabd702dfe101ed27e5dda
- [x] #614 -> 84222e72d5bfaaae42cd290d104fa093d58d6530
- [x] #720 -> e667e947d82d53738908c5f3ad4d0892639d074e

### Backports
- [x] Change unknown writers default behaviour: #639 -> #640
- [x] Added copy constructor to ResourceLimitedVector: #681 -> #728 
- [x] Add STRICT_REALTIME build option: #718 -> #730
- [x] SubscriberHistory improvements: #712 -> #731 + #743 
- [x] Eliminating use of acceptMsgDirectTo: #705 -> #741
- [x] Performance tests: #711 + #713 + #719 + #735 -> #732
- [x] WLP imporvements: #650 + #689 -> #742
- [x] Change cmake config directory if INSTALLER_PLATFORM is set #645 -> #746 
- [x] Remove FastRTPSGen #677 -> #746 

### Under evaluation
- [x] ~WriterProxy: #646 + #678~
- [x] ~Export addToCDRMessage function in DLL #679~
- [x] ~Separate temp_data and mutexes for volatile and stateless #702~
- [x] ~Removing unused directories #707~
- [x] ~Test improvements: #696~

**Comment by TSC21** [comment]
What `FastRTPSGen` version are you bringing along? Or does it just clone the latest version of it?

**Comment by MiguelCompany** [comment]
@TSC21 As FastRTPSGen has moved to another repository, and the code it generates is compatible with 1.8.x, we are considering to remove it for this release. That's why #677 is listed here

**Comment by TSC21** [comment]
> @TSC21 As FastRTPSGen has moved to another repository, and the code it generates is compatible with 1.8.x, we are considering to remove it for this release. That's why #677 is listed here

I am not sure about that. You do support IDL 4.2 in 1.8.x, right? So, should things like https://github.com/eProsima/IDL-Parser/pull/35 and https://github.com/eProsima/IDL-Parser/pull/36 be made available on `FastRTPSGen`, together with the Fast-RTPS 1.8.x release?
