### ISSUE TITLE
Release 1.9.3

### ISSUE THREAD

**Issue by MiguelCompany** [eProsima/Fast-RTPS#800]
### Bugfixes
- [x] Fix reception of ParameterList: #806
- [x] Fix history example destruction error: #805 

### Improvements
- [x] Build option to check documentation: Cherry-picking #813 -> b856e7bebec9c4c0e7d2da0eeeadeded4396d6c5

### Features
- [x] Adding filtering capabilities to the discovery mechanism: #845
- [x] Intra-process delivery:
    - [x] Intra-process delivery design: #839
    - [x] Internal methods to find endpoints on the local process: #841 
    - [x] Intra-process delivery implementation: #854

### Backports
- [x] Using thread local storage for RTPSMessageGroup_t: #763 -> #811 
- [x] Improvements on check_acked_status: #781 -> #812
- [x] Don't transform whitelist remote locators: #762 -> #765
- [x] Fixing helgrind issues: #776 -> #815
- [x] GUID_t refactor: #797 -> #840
- [x] Allocation QoS improvements:
  - [x] Allocation profiler improvements: #764 -> #816
  - [x] Remove fragment state vector on CacheChange_t: #789 -> #819
  - [x] Remove pitstop usage from StatelessReader: #796 -> #819
  - [x] Removing FragmentedChangePitStop: #846

**Comment by nuclearsandwich** [comment]
https://github.com/eProsima/Fast-RTPS/pull/819 re-introduced the communication failures between Fast-RTPS and RTI Connext in the ROS 2 communication tests. The test failures are still present on the latest 1.9.x branch as well.

Example CI build: https://ci.ros2.org/job/ci_linux/8586/
Example exact repos file: https://gist.githubusercontent.com/nuclearsandwich/9cf29e1add9721ab6454b505bea433c4/raw/6e1464600505ed16fa030bc3f1577ed000453edf/fastrtps.repos

**Comment by nuclearsandwich** [comment]
@MiguelCompany it looks like @laura-eprosima pushed the 1.9.3 bump a few hours ago but there are still regressions on this branch compared to 1.9.2. Is there a plan to address those before the release is cut?

**Comment by MiguelCompany** [comment]
> it looks like @laura-eprosima pushed the 1.9.3 bump a few hours ago but there are still regressions on this branch compared to 1.9.2.

In order to generate the documentation with the correct version number, we need it to be changed. We have done it so we can start preparing the docs and accelerate the release procedure.

> Is there a plan to address those before the release is cut?

Yes, it should have been addressed on #846. It seems that Connext is not respecting point 8.3.7.3.3 item 5 of the RTPS standard. We added some checks on #819 that have been relaxed on #846

**Comment by nuclearsandwich** [comment]
Thanks for the clarification. I'll give #846 a try and post results here.

**Comment by nuclearsandwich** [comment]
Our cross-vendor tests do pass with #846. Thanks.

**Comment by MiguelCompany** [comment]
@nuclearsandwich @dirk-thomas v1.9.3 is finally out. We would like to have it on Eloquent as soon as possible, at least on the testing packages.

We have run ROS2 tests successfully

**Comment by nuclearsandwich** [comment]
I've triggered CI for the v1.9.3 tag and it's running here

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8643)](http://ci.ros2.org/job/ci_linux/8643/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4486)](http://ci.ros2.org/job/ci_linux-aarch64/4486/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7050)](http://ci.ros2.org/job/ci_osx/7050/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8562)](http://ci.ros2.org/job/ci_windows/8562/)

Yesterday I released a 1.9.2 extension based on 141b778c66c4f1f7aeb5c55551c173e3237beae9 and that's what is currently released. I'll put another release out later today once CI comes back.
