### ISSUE TITLE
Performance improvements [6951]

### ISSUE THREAD

**Issue by richiware** [eProsima/Fast-RTPS#899]
* Improve sending piggyback heartbeat:
    * [x] 1.9.x [#887](https://github.com/eProsima/Fast-RTPS/pull/887)
    * [x] master [#888](https://github.com/eProsima/Fast-RTPS/pull/888)
* Improve sending GAP:
    * [x] 1.9.x [#889](https://github.com/eProsima/Fast-RTPS/pull/889)
    * [x] master [#890](https://github.com/eProsima/Fast-RTPS/pull/890)
* Improve ReaderHistory sorting:
   * [x] 1.9.x [#894](https://github.com/eProsima/Fast-RTPS/pull/894)
    * [x] master [#895](https://github.com/eProsima/Fast-RTPS/pull/895)
* Improve in consecutive calls to History::get_change:
   * [x] 1.9.x [#896](https://github.com/eProsima/Fast-RTPS/pull/896)
    * [x] master [#897](https://github.com/eProsima/Fast-RTPS/pull/897)

**Comment by MiguelCompany** [comment]
Created PR #905 with all the changes applied to 1.9.x

**Comment by MiguelCompany** [comment]
Changes have been applied to 1.9.x and master. Closing this meta-ticket.
